# Generated by Django 4.0.2 on 2022-02-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_member_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
